name: tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  example-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show Python environment
        run: |
          python --version
          pip --version
          python -c "import sys,platform;print('Platform:', platform.platform());print('Executable:', sys.executable)"
          pip freeze

      - name: Run example tests
        run: |
          python -u scripts/test_extractor_examples.py
